spring:
    application:
        name: rocketMQ-boot-producer
rocketmq:
    name-server: 192.168.30.129:9876
    producer:
        group: boot-producer-group
        enable-msg-trace: true #开启发送方的消息轨迹
server:
    port: 8081
