spring:
    application:
        name: seckill-web
    data:
        redis:
            host: localhost
            port: 6379
            database: 2

server:
    port: 8081
    tomcat:
        threads:
          max: 400

rocketmq:
    name-server: 192.168.30.129:9876
    producer:
        group: seckill-producer-group

