spring:
    application:
        name: seckill-service
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    data:
        redis:
            host: localhost
            port: 6379
            database: 2

rocketmq:
    name-server: 192.168.30.129:9876

mybatis:
    mapper-locations: classpath:mapper/*.xml
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
    port: 8082
